src/main/java/com/weady/weady/domain/user/controller/ExampleUserController.java
src/main/java/com/weady/weady/domain/user/dto/ExampleUserRequest.java
src/main/java/com/weady/weady/domain/user/dto/ExampleUserResponse.java
src/main/java/com/weady/weady/domain/user/mapper/UserMapper.java
src/main/java/com/weady/weady/domain/user/repository/UserRepository.java
src/main/java/com/weady/weady/domain/user/repository/UserRepositoryImpl.java
src/main/java/com/weady/weady/domain/user/service/ExampleUserService.java
src/main/java/com/weady/weady/global/common/error/errorCode/AuthErrorCode.java
src/main/java/com/weady/weady/global/util/SecurityUtil.java

> #3 
사용자 인증을 거치고 로그인한 사용자의 Authentication 객체가 저장되어있는 Spring Context Holder에서 해당 사용자의 ID(PK)를 가져오는 Utill 성 메소드를 작성했습니다.
추가적으로 코드 작성을 돕기위해 예시로 현재 로그인한 사용자의 정보를 반환하는 Exmaple 클래스들을 작성했습니다.
클라이언트에 리턴하는 값, 주석 작성 방식, Util 메소드 사용방식 등을 중점적으로 확인하시면 될 것 같습니다!

[FEAT] Auth / 인증객체 가져오는 메소드 작성, 예시코드 작성

---

.gitmodules

> ex) #이슈번호, #이슈번호
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?

[CHORE] Global / submodule 기본 브랜치 변경

---

src/main/java/com/weady/weady/domain/location/entity/Location.java

#20 
중기 예보 조회를 하기 위해서 필요한 지역코드 컬럼을 Locaiton 엔티티에 추가했습니다. 추가로 데이터도 같이 넣어놨습니다.
applicaiton.yml 의 hbm2ddl auto를 none으로 설정했습니다.

[FEAT] Weather / 중기예보 조회를 위한 지역코드 컬럼을 location에 추가

---

build.gradle
src/main/java/com/weady/weady/domain/board/controller/BoardController.java
src/main/java/com/weady/weady/global/config/SwaggerConfig.java

#23 
Swagger의 의존성이 현재 Spring Boot와는 호환되지 않는 이전 버전으로 되어있는 부분을 수정했습니다.
추가적으로 BoardController에 @RestController 가 아닌 @RestControllerAdvice 어노테이션이 붙어있었던 부분 수정했습니다.

[FIX] Swagger / 스웨거 설정 오류 수정

---

src/main/java/com/weady/weady/domain/curation/controller/CurationController.java
src/main/java/com/weady/weady/domain/curation/dto/CurationCategoryResponse.java
src/main/java/com/weady/weady/domain/curation/dto/CurationResponse.java
src/main/java/com/weady/weady/domain/curation/dto/Response/CurationByCurationIdResponseDto.java
src/main/java/com/weady/weady/domain/curation/dto/Response/CurationByLocationResponseDto.java
src/main/java/com/weady/weady/domain/curation/dto/Response/CurationCategoryResponseDto.java
src/main/java/com/weady/weady/domain/curation/dto/Response/CurationDto.java
src/main/java/com/weady/weady/domain/curation/dto/Response/ImgDto.java
src/main/java/com/weady/weady/domain/curation/mapper/CurationCategoryMapper.java
src/main/java/com/weady/weady/domain/curation/mapper/CurationMapper.java
src/main/java/com/weady/weady/domain/curation/repository/curation/CurationRepository.java
src/main/java/com/weady/weady/domain/curation/repository/curation/CurationRepositoryImpl.java
src/main/java/com/weady/weady/domain/curation/repository/curation/JpaCurationRepository.java
src/main/java/com/weady/weady/domain/curation/service/CurationService.java
src/main/java/com/weady/weady/domain/weadychive/controller/curation/WeadychiveController.java
src/main/java/com/weady/weady/domain/weadychive/dto/curation/Request/ScrapCurationRequestDto.java
src/main/java/com/weady/weady/domain/weadychive/dto/curation/Response/CurationDto.java
src/main/java/com/weady/weady/domain/weadychive/dto/curation/Response/ScrappedCurationByUserResponseDto.java
src/main/java/com/weady/weady/domain/weadychive/dto/curation/WeadychiveCurationRequest.java
src/main/java/com/weady/weady/domain/weadychive/dto/curation/WeadychiveCurationResponse.java
src/main/java/com/weady/weady/domain/weadychive/entity/WeadychiveCuration.java
src/main/java/com/weady/weady/domain/weadychive/mapper/curation/WeadychiveCurationMapper.java
src/main/java/com/weady/weady/domain/weadychive/repository/curation/JpaWeadychiveCurationRepository.java
src/main/java/com/weady/weady/domain/weadychive/repository/curation/WeadychiveCurationRepository.java
src/main/java/com/weady/weady/domain/weadychive/repository/curation/WeadychiveCurationRepositoryImpl.java
src/main/java/com/weady/weady/domain/weadychive/service/curation/WeadychiveCurationService.java

> #26 
> 웨디카이브 큐레이션 스크랩 기능 및 조회 기능 구현했습니다.

[FEAT] 웨디카이브 큐레이션 스크랩 관련 API 구현

---

src/main/java/com/weady/weady/domain/location/entity/Location.java
src/main/java/com/weady/weady/domain/location/repository/JpaLocationRepository.java
src/main/java/com/weady/weady/domain/location/repository/LocationRepository.java
src/main/java/com/weady/weady/domain/location/repository/LocationRepositoryImpl.java
src/main/java/com/weady/weady/domain/user/service/UserFavoriteLocationService.java

#36 
Location의 h_code -> hCode 로 변경
JpaRepository 직접 의존 -> 캡슐화로 변경

[REFACTOR] Location / 지역 hCode 변수명 변경

---

.github/workflows/ci-cd.yml

#39 
CI/CD 파이프라인을 위한 Github Action yml 파일 작성

[BUILD] global / github action yml 파일 작성

---

.dockerignore
Dockerfile

Docker image 빌드를 위한 dockerfile 작성

[BULID] Dockerfile 작성

---

src/main/java/com/weady/weady/domain/user/controller/UserController.java
src/main/java/com/weady/weady/domain/weather/entity/LocationWeatherShortDetail.java
src/main/java/com/weady/weady/domain/weather/entity/SkyCode.java
src/main/java/com/weady/weady/domain/weather/entity/WeatherMidDetail.java

#61 
중기예보 Entity를 작성했습니다.
단기예보 Entity를 일부 수정했습니다.

[FEAT] 중기예보 Entity 작성, 단기예보 Entity 수정

---

src/main/java/com/weady/weady/domain/user/controller/UserFavoriteLocationController.java
src/main/java/com/weady/weady/domain/user/dto/request/setDefaultLocationRequest.java
src/main/java/com/weady/weady/domain/user/service/UserFavoriteLocationService.java

> #55 
사용자의 기본 위치를 업데이트하는 비즈니스 로직을 구현

[FEAT] User / 유저 기본 위치 업데이트 api 구현

---

src/main/java/com/weady/weady/common/config/SwaggerConfig.java
src/main/java/com/weady/weady/domain/user/controller/UserFavoriteLocationController.java
src/main/java/com/weady/weady/domain/user/dto/request/setDefaultLocationRequest.java
src/main/java/com/weady/weady/domain/user/service/UserFavoriteLocationService.java

SSL 인증서 발급, 도메인 구매 및 설정에 따른 배포

[RELEASE] domain 설정 및 ssl 인증서 발급에 따른 배포

---

src/main/java/com/weady/weady/common/external/s3/MultipartJackson2HttpMessageConverter.java
src/main/java/com/weady/weady/domain/board/controller/BoardController.java
src/main/java/com/weady/weady/domain/board/dto/response/BoardHomeResponseDto.java
src/main/java/com/weady/weady/domain/board/dto/response/BoardResponseDto.java
src/main/java/com/weady/weady/domain/board/entity/board/Board.java
src/main/java/com/weady/weady/domain/board/entity/board/BoardImg.java
src/main/java/com/weady/weady/domain/board/mapper/BoardMapper.java
src/main/java/com/weady/weady/domain/board/service/BoardService.java

#88 
게시물에 이미지를 업로드하고, 조회할 수 있는 기능을 추가했습니다.
Swagger에서 파일과 Json 데이터를 동시에 받으면 Content-Type이 application/octet-stream으로 인식되는 문제가 있어서, 해당 타입을 처리하는 컨버터 클래스 MultipartJackson2HttpMessageConverter를  config/external/s3/ 에  추가했습니다!! 
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>

[FEAT] Board / 게시물 이미지 업로드 기능 추가

---

src/main/java/com/weady/weady/common/config/SecurityConfig.java
src/main/java/com/weady/weady/common/config/SwaggerConfig.java
src/main/java/com/weady/weady/domain/tags/dto/TemperatureTagResponseDto.java
src/main/java/com/weady/weady/domain/tags/entity/TemperatureTag.java
src/main/java/com/weady/weady/domain/tags/mapper/TagMapper.java

[RELEASE] dev > release 배포

---

src/main/java/com/weady/weady/domain/fashion/controller/FashionController.java
src/main/java/com/weady/weady/domain/user/controller/UserController.java

#116 
> ex) #이슈번호, #이슈번호
스웨거 가독성 향상을 위해서 API 엔드포인트의 작업에 대한 설명을 추가합니다.
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?

[REFACTOR] Fashion&MyPage @Operation 추가

---

src/main/java/com/weady/weady/common/config/TxConfig.java
src/main/java/com/weady/weady/domain/scheduler/DailySummaryScheduler.java
src/main/java/com/weady/weady/domain/scheduler/SnapshotScheduler.java
src/main/java/com/weady/weady/domain/scheduler/WeatherScheduler.java
src/main/java/com/weady/weady/domain/scheduler/service/DailySummaryService.java
src/main/java/com/weady/weady/domain/scheduler/service/ShortTermWeatherUpdateService.java
src/main/java/com/weady/weady/domain/scheduler/service/SnapshotService.java
src/main/java/com/weady/weady/domain/scheduler/service/WeatherUpdateService.java
src/main/java/com/weady/weady/domain/tags/dto/TemperatureTagResponseDto.java
src/main/java/com/weady/weady/domain/tags/entity/TemperatureTag.java
src/main/java/com/weady/weady/domain/tags/repository/season/SeasonRepository.java
src/main/java/com/weady/weady/domain/tags/repository/weather/WeatherRepository.java
src/main/java/com/weady/weady/domain/weather/entity/DailySummary.java
src/main/java/com/weady/weady/domain/weather/entity/LocationWeatherSnapshot.java
src/main/java/com/weady/weady/domain/weather/repository/DailySummaryRepository.java
src/main/java/com/weady/weady/domain/weather/repository/LocationWeatherSnapshotRepository.java
src/main/java/com/weady/weady/domain/weather/repository/WeatherShortDetailRepository.java
src/test/java/com/weady/weady/scheduler/DailySummaryTest.java

> #120 
Snapshot을 저장하고 데이터를 바탕으로 Summary를 만드는 스케쥴러를 구현합니다.

[FEAT] Scheduler / snapshot 저장, Summary 스케쥴러 

---

src/main/java/com/weady/weady/common/config/SwaggerConfig.java
src/main/java/com/weady/weady/domain/curation/dto/Response/ImgDto.java
src/main/java/com/weady/weady/domain/curation/mapper/CurationMapper.java
src/main/java/com/weady/weady/domain/curation/service/CurationService.java

> ex) #92 
> 큐레이션 카테고리와 위치에 따른 큐레이션 가져오기 부분에서 데일리 서머리 가져오기 부분 로직을 수정했습니다.

[FIX] 데일리 서머리 받아오기 로직 수정

---

src/main/java/com/weady/weady/common/config/SwaggerConfig.java
src/main/java/com/weady/weady/domain/board/controller/BoardController.java
src/main/java/com/weady/weady/domain/board/dto/response/BoardResponseDto.java
src/main/java/com/weady/weady/domain/board/entity/board/Board.java
src/main/java/com/weady/weady/domain/board/mapper/BoardMapper.java
src/main/java/com/weady/weady/domain/board/repository/CommentRepository.java
src/main/java/com/weady/weady/domain/board/service/BoardService.java
src/main/java/com/weady/weady/domain/board/service/CommentService.java

#129 
게시글 조회 시 해당 게시글의 총 댓글 개수를 나타내는 필드를 추가했습니다.
게시글 작성자 id가 현재 로그인 한 사용자의 id로 반환되는 오류를 수정했습니다!
게시물 수정 시 이미지를 제외한 내용만 수정 가능하도록 변경했습니다!!

[FEAT] Board / 댓글 개수 반환 로직 작성 및 유저 Id 반환 오류 수정

---

src/main/java/com/weady/weady/domain/fashion/service/FashionService.java
src/main/java/com/weady/weady/domain/user/repository/UserFavoriteLocationRepository.java

#136 
> ex) #이슈번호, #이슈번호
500 에러 난다고 하셔서 해결하였고, fashion 데이터베이스 온도 범위를 더 세밀하게 조정해서 예외가 발생하지 않도록 했습니다.
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?

[FIX] Fashion / 옷차림 요약 정보 조회 시 500 에러 해결

---

src/main/java/com/weady/weady/domain/weather/mapper/WeatherMapper.java

> #140 
> 데이터 포맷이 일치하지 않아서 발생했던 에러 해결

[FIX] Weatther / 중기예보 에러 수정 

---

src/main/java/com/weady/weady/domain/board/controller/BoardController.java
src/main/java/com/weady/weady/domain/board/entity/board/Board.java
src/main/java/com/weady/weady/domain/board/repository/BoardRepository.java
src/main/java/com/weady/weady/domain/board/repository/CommentRepository.java
src/main/java/com/weady/weady/domain/board/service/BoardService.java
src/main/java/com/weady/weady/domain/board/service/CommentService.java
src/main/java/com/weady/weady/domain/weadychive/dto/board/response/ScrapBoardResponseDto.java
src/main/java/com/weady/weady/domain/weadychive/mapper/board/WeadychiveBoardMapper.java

#147 
레포지토리 메서드를 수정하고 그에 따라 서비스 코드도 변경했습니다!

[REFACTOR] Board / 보드 및 댓글 전체 조회 로직 변경

---

src/main/java/com/weady/weady/domain/user/dto/response/GetMyPageResponse.java
src/main/java/com/weady/weady/domain/user/mapper/MyPageMapper.java
src/main/java/com/weady/weady/domain/user/service/MyPageService.java

[RELEASE] dev > release
